apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  type: NodePort
  selector:
    app: wisecow
  ports:
    - port: 4499          # Port inside the cluster
      targetPort: 4499    # Port on the container
      nodePort: 30001     # Port exposed on the host machine

